### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by belindabeach** [doomhz/coinnext#4]
Node Version: v6.0.0
Npm version: 3.8.6

npm install
make

Coinnext Core API is running on port 6000 in test mode
Coinnext is running on port 5000 in test mode
 0   -__,------,
 1   -__|  /\_/\ 
 0   -_~|_( x .x) 
     -_ ""  "" 

  0 passing (165ms)
  1 failing

  1) "before each" hook for "returns 200 ok":
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at tests/integrational/routes/orders.coffee:14:9
      at .<anonymous> (node_modules/sequelize/lib/emitters/custom-event-emitter.js:101:38)
      at module.exports.CustomEventEmitter.emit (node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
      at .<anonymous> (node_modules/sequelize/lib/dao-factory.js:902:19)
      at module.exports.CustomEventEmitter.emit (node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
      at .<anonymous> (node_modules/sequelize/lib/query-interface.js:981:19)
      at module.exports.CustomEventEmitter.emit (node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
      at node_modules/sequelize/lib/dialects/mysql/connector-manager.js:400:25
      at .<anonymous> (node_modules/sequelize/lib/emitters/custom-event-emitter.js:101:38)
      at module.exports.CustomEventEmitter.emit (node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
      at node_modules/sequelize/lib/dialects/mysql/connector-manager.js:243:28
      at node_modules/generic-pool/lib/generic-pool.js:271:11
      at node_modules/sequelize/lib/dialects/mysql/connector-manager.js:133:13
      at EventEmitter.<anonymous> (node_modules/sequelize/lib/dialects/mysql/connector-manager.js:338:7)
      at Handshake._callback (node_modules/sequelize/lib/dialects/mysql/connector-manager.js:320:19)
      at Handshake.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:101:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:205:24)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:62:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:37:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:73:28)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:535:20)

**Comment by rushiraj111** [comment]
same issue
